name: Data to Markdown

on:
  push:
    branches: [ main ]
    paths:
      - publications.bib
      - reagent_resources.csv
  workflow_dispatch:
jobs:
  data_2_md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pandoc
        sudo apt-get install pandoc-citeproc
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Fine tune data to markdown conversion
      id: ft
      shell: bash
      run: |
        convert_bib=0
        convert_reagents=0
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          convert_bib=1
          convert_reagents=1
        else
          if ! git diff --quiet HEAD\^ HEAD -- publications.bib src/ibex.csl; then
            convert_bib=1
          fi
          if ! git diff --quiet HEAD\^ HEAD -- reagent_resources.csv; then
            convert_reagents=1
          fi
        fi
        echo "convert_bib=$convert_bib" >> $GITHUB_OUTPUT
        echo "convert_reagents=$convert_reagents" >> $GITHUB_OUTPUT
        echo $convert_bib
        echo $convert_reagents
    - name: Print prev output
      run: |
        echo "Convert bib value:"
        echo ${{ steps.ft.outputs.convert_bib }}
        echo "Convert reagent value:"
        echo ${{ steps.ft.outputs.convert_reagents }}
    - name: Convert bibliography to markdown
      if: ${{ steps.ft.outputs.convert_bib == '1'}}
      run: |
        echo "Z convert bib"
        echo ${{ steps.ft.outputs.convert_bib }}
      #  pandoc --version
      #  python src/bib2md.py publications.bib src/ibex.csl docs/publications.md
    - name: Convert reagent-resources csv to markdown
      if: ${{ steps.ft.outputs.convert_reagents == '1'}}
      run: |
        echo "Z convert reagent"
        echo ${{ steps.ft.outputs.convert_reagents }}
        #python src/csv_reagent_resources_2_md_url.py reagent_resources.csv docs/supporting_material
    - name: Commit and push
      run: |
        if ! git diff --quiet; then
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add docs/reagent_resources.md docs/publications.md
          git commit -m "Adding converted markdowns."
          git push
        fi
