name: Data to Markdown

on:
  push:
    branches: [ main ]
    paths:
      - publications.bib
      - reagent_resources.csv
  workflow_dispatch:
jobs:
  data_2_md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pandoc
        sudo apt-get install pandoc-citeproc
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Fine tuning execution
      id: ft
      shell: bash
      run: |
        if [ ${{ github.event_name == 'workflow_dispatch' }}='true' ]; then
           echo "Z Convert all"
        else
          if [ $(git diff --quiet HEAD\^ HEAD -- publications.bib src/ibex.csl docs/publications.md) ]; then
            echo "Z Convert bib"
          fi
          if [$(git diff --quiet HEAD\^ HEAD -- publications.bib .github/workflows/data2md.yml)]; then
            echo "Z Convert data2md.yml"
          fi
        fi
    - name: Convert bibliography to markdown
      if: ${{ steps.ft.outputs.convert_bib }}
      run: |
        pandoc --version
        python src/bib2md.py publications.bib src/ibex.csl docs/publications.md
    - name: Convert reagent-resources csv to markdown
      run: |
        python src/csv_reagent_resources_2_md_url.py reagent_resources.csv docs/supporting_material
    - name: Commit and push
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git add docs/reagent_resources.md docs/publications.md
        git commit -m "Adding converted markdowns."
        git push
